# Changes here will be overwritten by Copier
_commit: v1.0.0-3-g3544c4e
_src_path: python-project-template
author_email: email.placeholder@someplace.special
author_name: Name Placeholder
module_name: example_project
project_name: example_project
